sudo: false
language: python

os:
  - linux
  - osx

python:
    # We don't actually use the Travis Python, but this keeps it organized.
    - "2.7"
    - "3.4"
    - "3.5"

addons:
    apt:
        packages:
            - libatlas-dev
            - libatlas-base-dev
            - liblapack-dev
            - gfortran
            - libhdf5-serial-dev

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]
      then
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
      elif [[ "$TRAVIS_OS_NAME" == "linux" ]]
      then
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi

    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda update --yes conda

    # Useful for debugging any issues with conda
    - conda info -a

    - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose h5py cython pandas xlrd

    - pip install emcee uncertainties lmfit matplotlib jupyter


install:
    - python setup.py install

script:
    - python runtests.py

notifications:
    # Perhaps we should have status emails sent to the mailing list, but
    # let's wait to see what people think before turning that on.
    email: false
